import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Derecho</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Bienvenido a plataforma de peticiones de derecho
        </h1>

        <p className={styles.description}>
         Selecciona la opción{' '}
         
        </p>

        <div className={styles.grid}>
          <Link href="/transito-y-transporte">
          <a  className={styles.card}>
            <h2> Transito &rarr;</h2>
            <p>Genera Petición de revocatoria y subsidiaria petición de información </p>
          </a>
          </Link>
         

         
           
          
         
        </div>
      </main>

    
    </div>
  )
}
