import Head from "next/head";
import styles from "../styles/Home.module.css";
import HomeSection from "../src/components/HomeSection";
import client from "../client";

export default function HomePage({authorData}) {
  return (
    <>
  
      <div className={styles.container}>
        <Head>
          <title>Derecho</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    
        <HomeSection authorData={authorData} />
    </>
  );
}

const queryBlogHome = `
*[_type == 'author']{
  _id,
  name,
  'slug': slug.current,
  'imageLawyer' : image.asset->url,
  bio,
  description
  }[0...5]
`;

export async function getStaticProps() {
  const authorData = await client.fetch(queryBlogHome);

  return {
    props: {
      authorData
    },
    revalidate: 10
  };
}
